[theme]
base = "light"
primaryColor = "#0891B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0B1220"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
